version: '3.8'
services:
  claude-ssh:
    build:
      # Указываем Portainer, что Dockerfile лежит в папке "claude-ssh"
      context: ./claude-ssh
    container_name: claude-ssh-server
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      # Используем постоянное хранилище Portainer (не слетает при обновлениях)
      - /home/umbrel/umbrel/app-data/portainer/claude-projects:/home/dev/projects