version: '3.8'
services:
  app_proxy:
    environment:
      # ИСПРАВЛЕНО: Указываем полное, правильное имя хоста
      APP_HOST: may4vfx-custom-apps-claude-ssh_app_1
      APP_PORT: 22

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/projects:/home/dev/projects
