version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Копируем конфигурацию сети и прав из pi-hole/tailscale
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/projects:/home/dev/projects