version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Используем сеть хоста
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/projects:/home/dev/projects
